ca_root = "/path/ca.pem"

[[gateway]]
listener = "[::]:443"
cert = "/path/fullchain.pem"
key  = "/path/privkey.pem"
allow_origin = ["https://example.com"]

  [[gateway.lb_backends]]
  addr = "127.0.0.1:443"
  sni = "m.mm29942.com"

  [[gateway.endpoint]]
  prefix = "/lead"
  addr = "127.0.0.1:8000"
  tls = false

[[gateway]]
listener = "[::]:8443"
cert = "/path/second/fullchain.pem"
key  = "/path/second/privkey.pem"
allow_origin = ["https://other.com"]

  [[gateway.endpoint]]
  prefix = "/api"
  addr = "127.0.0.1:5000"
  tls = false
