listener = "[::]:443"
cert = "/path/fullchain.pem"
key  = "/path/privkey.pem"
ca_root = "/path/ca.pem"
allow_origin = ["https://example.com"]
round_robin = true
client_bind_to_ipv4 = []
client_bind_to_ipv6 = []
queue_cap = 100
default_header_timeout_ms = 3000
default_body_timeout_ms = 5000
base_prefix = "/api"
prepend_base_prefix = true

[metrics]
addr = "127.0.0.1:9100"
path = "/metrics"

[[lb_backends]]
addr = "127.0.0.1:443"
tls = true
sni = "m.mm29942.com"

[[endpoint]]
prefix = "lead"
addr = "127.0.0.1:8000"
tls = false
sni = "m.mm29942.com"

[[endpoint]]
prefix = "leads"
addr = "127.0.0.1:6443"
tls = true
sni = "m.mm29942.com"
connect_timeout_ms = 1000
read_timeout_ms = 2000
header_timeout_ms = 4000
body_timeout_ms = 6000

[[endpoint]]
prefix = "/support"
addr = "127.0.0.1:9443"
tls = true
sni = "m.mm29942.com"
